### ISSUE TITLE
Help with connector setup

### ISSUE THREAD

**Issue by jigishadhawan** [Templum/rabbitmq-connector#104]
I have set up openfaas, rabbitmq on a kubernetes cluster (set up cluster with kind) on a windows machine but linux container. Both openfaas and rabbitmq seem to be working as expected.

However I'm facing an issue when deploying the rabbitmq-connector code. I have the Path_to_topology variable as below in the yaml file

-         name: PATH_TO_TOPOLOGY
          value: "./csharp/hack/test/artifacts/example_topology.yaml"

But whatever path I give I get the following error for the container "During Config validation provided topology is either non existing or does not end with .yaml occurred.". 

Could you please suggest how I should define the path? I have tried the following values as well

a. Given absolute path:- C:/Users/jdhawan/csharp/hack/test/artifacts/example_topology.yaml
b. Given the same like :-  C:\\Users\\jdhawan\\csharp\\hack\\test\\artifacts\\example_topology.yaml
c. Given relative path like :-  (since i have changed my directory to C:/Users/jdhawan/csharp/hack/test).-  /artifacts/example_topology.yaml

I have also used the below
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-connector
  namespace: openfaas
spec:
  selector:
    matchLabels:
      app: rabbitmq-connector
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-connector
    spec:
      containers:
      - name: connector
        image: templum/rabbitmq-connector:develop
        imagePullPolicy: Always
        env:
        - name: basic_auth
          value: "true"
        - name: secret_mount_path
          value: "/etc/openfaas"
        - name: OPEN_FAAS_GW_URL
          value: "http://127.0.0.1:8080"
        - name: RMQ_TOPICS
          value: "demo"
        - name: RMQ_HOST
          value: "http://127.0.0.1"
        - name: RMQ_PORT
          value: "5672"
        - name: RMQ_USER
          value: "user"
        - name: RMQ_PASS
          value: "pass"
        - name: REQ_TIMEOUT
          value: "30s"
        - name: TOPIC_MAP_REFRESH_TIME
          value: "30s"             
        resources: # Adjust them to suite your needs
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1024Mi
            cpu: 2
        volumeMounts:
          - name: basic-auth
            readOnly: true
            mountPath: "/etc/openfaas"
          - name: config-volume
            mountPath: /artifacts/cfg/example-topology.yaml
            subPath: example-topology.yaml             
      volumes:
        - name: basic-auth
          secret:
            secretName: basic-auth
        - name: config-volume
          configMap:
            name: topology-test

Any help is greatly appreciated. Also is there a way to know as to what path is it trying to form and cant get to it?

**Comment by Templum** [comment]
So from what I see `PATH_TO_TOPOLOGY` should be `/artifacts/cfg/example-topology.yaml` as this what you specify in the volume. Please avoid using relative paths, as it will be relative to the go executable. Not the workdir that you might specified in the Docker image.

Further, you can always try to attach to your k8s and checkout, if you really see a file there.

**Comment by Templum** [comment]
Further `OPEN_FAAS_GW_URL` & `RMQ_HOST` look wrong. As on K8S `127.0.0.1` will be not your local pc, but the local container/pod.

**Comment by jigishadhawan** [comment]
Thanks Simon. Everything is working now

For anyone else looking I followed these steps:-

This is using Gitbash on windows
1. $ arkade install openfaas --basic-auth=false
2. $ kubectl rollout status -n openfaas deploy/gateway
3. $ kubectl port-forward -n openfaas svc/gateway 8080:8080 &
4. opened another git bash terminal and confirmed faas-cli. Not i already had faas-cli installed so didnt need to install it here
5. faas-cli list - this lists the functions if they are running
6. faas-cli store list
7. faas-cli store deploy figlet - also deployed function
8. helm install rabbit -n openfaas -f ./rabbit-values.yaml bitnami/rabbitmq - i deployed this in the openfaas namespace
9. kubectl port-forward --namespace openfaas svc/rabbit-rabbitmq 5672:5672 - run this for port forward so that with code u can send the data to something like "amqp://user:pass@127.0.0.1:5672"
10. opened another terminal
11. kubectl port-forward --namespace openfaas svc/rabbit-rabbitmq 15672:15672 - run this so that u can access rabbitmq interface from browser
12. kubectl get po -n openfaas - wanted to check all the pods in openfaas namespace
13. kubectl get svc -n openfaas - this will help us get the ClusterIP which will be used in the rabbitmq-connector.yaml file. Note the ClusterIP of gateway and rabbit-rabbitmq
14.  kubectl get cm -n openfaas - gets all configmaps in openfaas namespace
15.  kubectl create cm top-test --namespace=openfaas --from-file=/artifacts/cfg/topology.yaml  - created configmap for topology.

Contents of topology.yaml 
* - name: AEx
  topics: [demo]
  declare: true
  type: "direct"
  durable: false
  auto-deleted: false
  
  
16.  kubectl apply -f ./artifacts/rabbitmq-connector.yaml

Contents of rabbitmq-connector yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-connector
  namespace: openfaas
spec:
  selector:
    matchLabels:
      app: rabbitmq-connector
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-connector
    spec:
      containers:
      - name: connector
        image: templum/rabbitmq-connector:develop
        imagePullPolicy: Always
        env:
        - name: basic_auth
          value: "false"
        - name: OPEN_FAAS_GW_URL
          value: "http://clusterIP:8080"  # this was the gateway clusterIP replace value
        - name: RMQ_TOPICS
          value: "demo"
        - name: RMQ_HOST
          value: "clusterIP" # this was the rabbitmq clusterIP replace value
        - name: RMQ_PORT
          value: "5672"
        - name: RMQ_USER
          value: "user"
        - name: RMQ_PASS
          value: "pass"
        - name: REQ_TIMEOUT
          value: "30s"
        - name: TOPIC_MAP_REFRESH_TIME
          value: "30s"
        - name: PATH_TO_TOPOLOGY
          value: "/artifacts/cfg/topology.yaml"        
        resources: # Adjust them to suite your needs subPath: topology.yaml
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1024Mi
            cpu: 2
        volumeMounts:
          - name: top-test
            mountPath: "/artifacts/cfg/topology.yaml" 
            subPath: topology.yaml
      volumes:
        - name: top-test
          configMap:
            name: top-test

17.  kubectl get po -n openfaas - make sure all pods are running
18.  kubectl logs rabbitmq-connector-5b59f648c-kvb5t -n openfaas -f - then check  logs for connector to ensure it is able to connect 
19. deployed openfaas function - faas-cli store deploy figlet --annotation topic="demo" --name integration
20. run rabbitmq producer to generate topic data. note i have .net rabbitmq producer application for this
21. open openfaas portal at http://127.0.0.1:8080/ui/ and confirm the invocation count for the function after generating the data
