### ISSUE TITLE
Openfaas functions are not being triggered with rabbitmq connector

### ISSUE THREAD

**Issue by jigishadhawan** [Templum/rabbitmq-connector#108]
# General Information

**Environment**

Docker: v20.10.5
Kubernetes: v1.19.7
Other: []

**Connector Version**
[Version: dev Commit: aa10f5d]

# Bug Details

**Describe the bug**
Openfaas functions are not being triggered with rabbitmq connector. It was working before this new commit was made yesterday

**Expected behaviour**
The openfaas function should trigger

**Steps to Reproduce**

This is using Gitbash on windows
1. $ arkade install openfaas --basic-auth=false
2. $ kubectl rollout status -n openfaas deploy/gateway
3. $ kubectl port-forward -n openfaas svc/gateway 8080:8080 &
4. opened another git bash terminal and confirmed faas-cli. Not i already had faas-cli installed so didnt need to install it here
5. faas-cli list - this lists the functions if they are running
6. faas-cli store list
7. faas-cli store deploy figlet - also deployed function
8. helm install rabbit -n openfaas -f ./rabbit-values.yaml bitnami/rabbitmq - i deployed this in the openfaas namespace
9. kubectl port-forward --namespace openfaas svc/rabbit-rabbitmq 5672:5672 - run this for port forward so that with code u can send the data to something like "amqp://user:pass@127.0.0.1:5672"
10. opened another terminal
11. kubectl port-forward --namespace openfaas svc/rabbit-rabbitmq 15672:15672 - run this so that u can access rabbitmq interface from browser
12. kubectl get po -n openfaas - wanted to check all the pods in openfaas namespace
13. kubectl get svc -n openfaas - this will help us get the ClusterIP which will be used in the rabbitmq-connector.yaml file. Note the ClusterIP of gateway and rabbit-rabbitmq
14.  kubectl get cm -n openfaas - gets all configmaps in openfaas namespace
15.  kubectl create cm top-test --namespace=openfaas --from-file=/artifacts/cfg/topology.yaml  - created configmap for topology.

Contents of topology.yaml 
- name: DEx
  topics: [abc]
  declare: true
  type: "direct"
  durable: false
  auto-deleted: false
  
  
16.  kubectl apply -f ./artifacts/rabbitmq-connector.yaml

Contents of rabbitmq-connector yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-connector
  namespace: openfaas
spec:
  selector:
    matchLabels:
      app: rabbitmq-connector
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-connector
    spec:
      containers:
      - name: connector
        image: templum/rabbitmq-connector:develop
        imagePullPolicy: Always
        env:
        - name: basic_auth
          value: "false"
        - name: OPEN_FAAS_GW_URL
          value: "http://10.96.107.112:8080"  # this was the gateway clusterIP
        - name: RMQ_TOPICS
          value: "demo"
        - name: RMQ_HOST
          value: "10.96.194.90" # this was the rabbitmq clusterIP
        - name: RMQ_PORT
          value: "5672"
        - name: RMQ_USER
          value: "user"
        - name: RMQ_PASS
          value: "pass"
        - name: REQ_TIMEOUT
          value: "30s"
        - name: TOPIC_MAP_REFRESH_TIME
          value: "30s"
        - name: PATH_TO_TOPOLOGY
          value: "/artifacts/cfg/topology.yaml"        
        resources: # Adjust them to suite your needs subPath: topology.yaml
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1024Mi
            cpu: 2
        volumeMounts:
          - name: top-test
            mountPath: "/artifacts/cfg/topology.yaml" 
            subPath: topology.yaml
      volumes:
        - name: top-test
          configMap:
            name: top-test

17.  kubectl get po -n openfaas - make sure all pods are running
18.  kubectl logs rabbitmq-connector-5b59f648c-kvb5t -n openfaas -f - then check  logs for connector to ensure it is able to connect 
19. deployed openfaas function - faas-cli store deploy figlet --annotation topic="demo" --name integration
20. run rabbitmq producer to generate topic data. note i have .net rabbitmq producer application for this
21. open openfaas portal at http://127.0.0.1:8080/ui/ and confirm the invocation count for the function after generating the data
22.  faas-cli deploy -f csharp.yml --annotation topic="demo" --name csharp - this is runnign from local Git location

**Screenshots/Logs**
If applicable, add screenshots/logs to help explain your problem.

Logs of connector
2021/04/08 23:03:13 maxprocs: Updating GOMAXPROCS=2: determined from CPU quota
2021/04/08 23:03:13 OpenFaaS RabbitMQ Connector [Version: dev Commit: aa10f5d]
2021/04/08 23:03:13 Started Cache Task which populates the topic map
2021/04/08 23:03:13 Started RabbitMQ <=> OpenFaaS Connector
2021/04/08 23:03:13 Will now establish connection to amqp://10.96.72.115:5672
2021/04/08 23:03:13 Crawling namespaces for functions
2021/04/08 23:03:13 Crawling for functions
2021/04/08 23:03:13 Crawling finished will now refresh the cache
2021/04/08 23:03:13 Update cache with 2 entries
2021/04/08 23:03:13 Successfully established connection to Rabbit MQ Cluster
2021/04/08 23:03:13 Factory is configured for exchange DEx
2021/04/08 23:03:13 Successfully declared exchange DEx of type direct { Durable: false Auto-Delete: false }
2021/04/08 23:03:13 Successfully declared Queue OpenFaaS_DEx_abc
2021/04/08 23:03:13 Successfully bound Queue OpenFaaS_DEx_abc to exchange DEx
2021/04/08 23:03:13  [*] Waiting for messages. To exit press CTRL+C
2021/04/08 23:03:43 Crawling namespaces for functions
2021/04/08 23:03:43 Crawling for functions
2021/04/08 23:03:43 Crawling finished will now refresh the cache
2021/04/08 23:03:43 Update cache with 2 entries
2021/04/08 23:04:13 Crawling namespaces for functions
2021/04/08 23:04:13 Crawling for functions
2021/04/08 23:04:13 Crawling finished will now refresh the cache
2021/04/08 23:04:13 Update cache with 2 entries
2021/04/08 23:04:43 Crawling namespaces for functions
2021/04/08 23:04:43 Crawling for functions
2021/04/08 23:04:43 Crawling finished will now refresh the cache
2021/04/08 23:04:43 Update cache with 2 entries
2021/04/08 23:05:13 Crawling namespaces for functions
2021/04/08 23:05:13 Crawling for functions
2021/04/08 23:05:13 Crawling finished will now refresh the cache
2021/04/08 23:05:13 Update cache with 2 entries
2021/04/08 23:05:43 Received message for topic OpenFaaS_DEx_abc that did not match subscribed topic abc will reject it
2021/04/08 23:05:43 Crawling namespaces for functions
2021/04/08 23:05:43 Crawling for functions
2021/04/08 23:05:43 Crawling finished will now refresh the cache
2021/04/08 23:05:43 Update cache with 2 entries
2021/04/08 23:06:13 Crawling namespaces for functions
2021/04/08 23:06:13 Crawling for functions
2021/04/08 23:06:13 Crawling finished will now refresh the cache
2021/04/08 23:06:13 Update cache with 2 entries
2021/04/08 23:06:43 Crawling namespaces for functions
2021/04/08 23:06:43 Crawling for functions
2021/04/08 23:06:43 Crawling finished will now refresh the cache
2021/04/08 23:06:43 Update cache with 2 entries
2021/04/08 23:07:13 Crawling namespaces for functions
2021/04/08 23:07:13 Crawling for functions
2021/04/08 23:07:13 Crawling finished will now refresh the cache
2021/04/08 23:07:13 Update cache with 2 entries
2021/04/08 23:07:43 Crawling namespaces for functions
2021/04/08 23:07:43 Crawling for functions
2021/04/08 23:07:43 Crawling finished will now refresh the cache
2021/04/08 23:07:43 Update cache with 2 entries
2021/04/08 23:08:13 Crawling namespaces for functions
2021/04/08 23:08:13 Crawling for functions
2021/04/08 23:08:13 Crawling finished will now refresh the cache
2021/04/08 23:08:13 Update cache with 2 entries
2021/04/08 23:08:43 Crawling namespaces for functions
2021/04/08 23:08:43 Crawling for functions
2021/04/08 23:08:43 Crawling finished will now refresh the cache
2021/04/08 23:08:43 Update cache with 2 entries
2021/04/08 23:09:13 Crawling namespaces for functions
2021/04/08 23:09:13 Crawling for functions
2021/04/08 23:09:13 Crawling finished will now refresh the cache
2021/04/08 23:09:13 Update cache with 2 entries
2021/04/08 23:09:43 Crawling namespaces for functions
2021/04/08 23:09:43 Crawling for functions
2021/04/08 23:09:43 Crawling finished will now refresh the cache
2021/04/08 23:09:43 Update cache with 2 entries
2021/04/08 23:10:13 Crawling namespaces for functions
2021/04/08 23:10:13 Crawling for functions
2021/04/08 23:10:13 Crawling finished will now refresh the cache
2021/04/08 23:10:13 Update cache with 2 entries
2021/04/08 23:10:43 Crawling namespaces for functions
2021/04/08 23:10:43 Crawling for functions
2021/04/08 23:10:43 Crawling finished will now refresh the cache
2021/04/08 23:10:43 Update cache with 2 entries
2021/04/08 23:11:13 Crawling namespaces for functions
2021/04/08 23:11:13 Crawling for functions
2021/04/08 23:11:13 Crawling finished will now refresh the cache
2021/04/08 23:11:13 Update cache with 2 entries
2021/04/08 23:11:43 Crawling namespaces for functions
2021/04/08 23:11:43 Crawling for functions
2021/04/08 23:11:43 Crawling finished will now refresh the cache
2021/04/08 23:11:43 Update cache with 2 entries
2021/04/08 23:12:13 Crawling namespaces for functions
2021/04/08 23:12:13 Crawling for functions
2021/04/08 23:12:13 Crawling finished will now refresh the cache
2021/04/08 23:12:13 Update cache with 2 entries
2021/04/08 23:12:43 Crawling namespaces for functions
2021/04/08 23:12:43 Crawling for functions
2021/04/08 23:12:43 Crawling finished will now refresh the cache
2021/04/08 23:12:43 Update cache with 2 entries
2021/04/08 23:13:13 Crawling namespaces for functions
2021/04/08 23:13:13 Crawling for functions
2021/04/08 23:13:13 Crawling finished will now refresh the cache
2021/04/08 23:13:13 Update cache with 2 entries
2021/04/08 23:13:43 Crawling namespaces for functions
2021/04/08 23:13:43 Crawling for functions
2021/04/08 23:13:43 Crawling finished will now refresh the cache
2021/04/08 23:13:43 Update cache with 2 entries
2021/04/08 23:14:13 Crawling namespaces for functions
2021/04/08 23:14:13 Crawling for functions
2021/04/08 23:14:13 Crawling finished will now refresh the cache
2021/04/08 23:14:13 Update cache with 2 entries
2021/04/08 23:14:43 Crawling namespaces for functions
2021/04/08 23:14:43 Crawling for functions
2021/04/08 23:14:43 Crawling finished will now refresh the cache
2021/04/08 23:14:43 Update cache with 2 entries
2021/04/08 23:15:13 Crawling namespaces for functions
2021/04/08 23:15:13 Crawling for functions
2021/04/08 23:15:13 Crawling finished will now refresh the cache
2021/04/08 23:15:13 Update cache with 2 entries
2021/04/08 23:15:43 Crawling namespaces for functions
2021/04/08 23:15:43 Crawling for functions
2021/04/08 23:15:43 Crawling finished will now refresh the cache
2021/04/08 23:15:43 Update cache with 2 entries
2021/04/08 23:16:13 Crawling namespaces for functions
2021/04/08 23:16:13 Crawling for functions
2021/04/08 23:16:13 Crawling finished will now refresh the cache
2021/04/08 23:16:13 Update cache with 2 entries
2021/04/08 23:16:43 Crawling namespaces for functions
2021/04/08 23:16:43 Crawling for functions
2021/04/08 23:16:43 Crawling finished will now refresh the cache
2021/04/08 23:16:43 Update cache with 2 entries
2021/04/08 23:17:13 Crawling namespaces for functions
2021/04/08 23:17:13 Crawling for functions
2021/04/08 23:17:13 Crawling finished will now refresh the cache
2021/04/08 23:17:13 Update cache with 2 entries
2021/04/08 23:17:43 Crawling namespaces for functions
2021/04/08 23:17:43 Crawling for functions
2021/04/08 23:17:43 Crawling finished will now refresh the cache
2021/04/08 23:17:43 Update cache with 2 entries
2021/04/08 23:18:13 Crawling namespaces for functions
2021/04/08 23:18:13 Crawling for functions
2021/04/08 23:18:13 Crawling finished will now refresh the cache
2021/04/08 23:18:13 Update cache with 2 entries
2021/04/08 23:18:43 Crawling namespaces for functions
2021/04/08 23:18:43 Crawling for functions
2021/04/08 23:18:43 Crawling finished will now refresh the cache
2021/04/08 23:18:43 Update cache with 2 entries
2021/04/08 23:19:13 Crawling namespaces for functions
2021/04/08 23:19:13 Crawling for functions
2021/04/08 23:19:13 Crawling finished will now refresh the cache
2021/04/08 23:19:13 Update cache with 2 entries

Using a .net application to publish message to RabbitMQ. Sample code below

  static void Main(string[] args)
        {          
		   
            var factory = new ConnectionFactory
            {
                Uri = new Uri("amqp://user:pass@127.0.0.1:5672")
            };

            //amqp://127.0.0.1:5672/
            using var connection = factory.CreateConnection();
            using var channel = connection.CreateModel();
          

          
            channel.ExchangeDeclare(exchange: "DEx", type: "direct");
           
            var message = new { Name = "Producer", Message = "Hello" };
        
            channel.BasicPublish(exchange: "DEx",
                    routingKey: "abc",
                    basicProperties: null,
                    body: body);

            Console.WriteLine(" [x] Sent {0}", message);
        }

**Comment by Templum** [comment]
@jigishadhawan the latest commit changed a GitHub action, so highly doubt that it has any impact. From your logs I can see that a message was received, but did not match the correct label: `Received message for topic OpenFaaS_DEx_abc that did not match subscribed topic abc will reject it`. 
So from this log line, it looks like you send something with routingkey: `OpenFaaS_DEx_abc`, where it should be simply `abc`.
Could you double-check that locally your routing key is consistent across all areas (functions, topology & publisher)

Additionally, the pipeline with the integration test clearly worked: https://github.com/Templum/rabbitmq-connector/runs/2295391761

**Comment by jigishadhawan** [comment]
Hello @Templum 

I did see that message and i generated more messages for the queue

The command for setting up function

faas-cli store deploy figlet --annotation topic="abc" --name integration

Topology.yaml file contents
- name: DEx
  topics: [abc]
  declare: true
  type: "direct"
  durable: false
  auto-deleted: false

.net code for sending message
var factory = new ConnectionFactory
        {
            Uri = new Uri("amqp://user:pass@127.0.0.1:5672")
        };

        //amqp://127.0.0.1:5672/
        using var connection = factory.CreateConnection();
        using var channel = connection.CreateModel();
      

      
        channel.ExchangeDeclare(exchange: "DEx", type: "direct");
       
        var message = new { Name = "Producer", Message = "Hello" };
    
        channel.BasicPublish(exchange: "DEx",
                routingKey: "abc",
                basicProperties: null,
                body: body);


Can you please review it and let me know if there is a name mismatch anywhere. I see all the messages in rabbitmq under Unacked column.

**Comment by Templum** [comment]
Hello @jigishadhawan,

I performed the following steps in an attempt to locally reproduce the issues and was not able to do so, the only major difference is the producer. As I leverage the Rabbit MQ UI. Below I will explain my steps, please try to follow the publishing steps on the Rabbit MQ UI as well. Because this lets us eliminate potential issues with the `.net`-Producer.


I deployed OpenFaaS & Rabbit MQ as you shared to a new k3d cluster (k8s), forwarded the relevant ports to localhost, and started the connector with the shared topology:

```yaml
- name: DEx
  topics: [abc]
  declare: true
  type: "direct"
  durable: false
  auto-deleted: false
```

The function was deployed as you shared it here as well:
![FN_Deploy](https://user-images.githubusercontent.com/7703616/114209518-fcab6a80-995e-11eb-9fef-1e3a232d56c6.png)

I logged into the Rabbit MQ Ui and went to the Exchange List and identified our `DEx`:
![Exchange_List](https://user-images.githubusercontent.com/7703616/114210089-a4c13380-995f-11eb-955f-13734a6a0ca0.png)

Then I used the second form to publish a message (text) to the specific routing key:
![Invocation_Via_Ui](https://user-images.githubusercontent.com/7703616/114210149-b6a2d680-995f-11eb-99af-cf26ba1de8d6.png)

And I'm able to see the invocations coming in and being correctly processed:
![Logs](https://user-images.githubusercontent.com/7703616/114210252-d639ff00-995f-11eb-99e9-a44d2fd1c9ad.png)

**Comment by Templum** [comment]
@jigishadhawan additional to the above instructions, I created a small producer in go which I added with #109. With which I was also not able to reproduce your issues.

**Comment by jigishadhawan** [comment]
Thanks @Templum . It seems to be working fine now. My issue was with openfaas.

I reinstalled it and it seems to be triggering correctly now

**Comment by jigishadhawan** [comment]
I had another question on how to receive the input in code from rabbitmq when the openfaas function gets triggered.

**Comment by jigishadhawan** [comment]
thanks for the help!!

**Comment by Templum** [comment]
@jigishadhawan btw your step 13 is obsolete, you don't need Cluster IP of gateway. Actually, you can leverage the service name, as this will automatically be resolved to the Cluster IP

**Comment by jigishadhawan** [comment]
thanks. I will give it a try

**Comment by shivupoojar** [comment]
@Templum  I am receiving the similar issue, logs of the connector shows like this "Received message for topic **OpenFaaS_openfaas_hello** that did not match subscribed topic **hello** will reject it"

**Comment by Templum** [comment]
That is not an issue, seems like you did not setup the function correctly. Clearly a missmatch
