### ISSUE TITLE
[BUG] Messages not acknowledged

### ISSUE THREAD

**Issue by oktapodia** [Templum/rabbitmq-connector#110]
# General Information

**Environment**

Docker: [20.10.5]
Kubernetes: []
Other: []

**Connector Version**
Tag: templum/rabbitmq-connector:latest
Sha: 8db570831cf6b595f2beb4481b2f121283053b34502ff0adca257b3426eb3260

# Bug Details

**Describe the bug**

The connection between the rabbitmq-connector and rabbitmq is working well (thank you for this project!) however, my messages never get acknowledged, they stay in the queue if they are successfully processed or not.

I can't seem to find what should be the message returned by the function to trigger that, I am currently returning that

```
    return {
        statusCode, // the HTTP status code
         headers: {
           'content-type': 'application/json' // I also tried with the default content-type without any success
        },
        Body: content, // can be anything
    };
```

(Also, I don't seem to be able to set a different status code)

**Expected behaviour**
Please give a clear and concise description of what you expected to happen.

Manually or automatically acknowledge the message on response

**Steps to Reproduce**

If possible provide a step by step guide on how to reproduce the issue.
Please make sure to also highlight environmental factors.

**Screenshots/Logs**
If applicable, add screenshots/logs to help explain your problem.

![image](https://user-images.githubusercontent.com/2752200/114270109-86604400-9a02-11eb-87c1-99a0fb74e93e.png)

**Comment by Templum** [comment]
Could you please share the output of the connector, the shared information does not really allow me any analysis of the issue.

That a side, generally speaking, calls to the function should yield a `200 - OK` to be considered passing. Is that the case for you? Additionally, you could  try the latest `develop`-branch as yesterday I just confirmed the correct behaviour (see also #108)

**Comment by oktapodia** [comment]
Sorry for the late answer, here are the logs

```
rabbitmq-connector_1  | 2021/04/12 09:10:37 OpenFaaS RabbitMQ Connector [Version: v1.0.1 Commit: fabd9a8]
rabbitmq-connector_1  | 2021/04/12 09:10:37 Started Cache Task which populates the topic map
rabbitmq-connector_1  | 2021/04/12 09:10:37 Started RabbitMQ <=> OpenFaaS Connector
rabbitmq-connector_1  | 2021/04/12 09:10:37 Will now establish connection to amqp://rabbitmq:5672
rabbitmq-connector_1  | 2021/04/12 09:10:37 Successfully established connection to Rabbit MQ Cluster
rabbitmq-connector_1  | 2021/04/12 09:10:37 Factory is configured for exchange my-delay-exchange
rabbitmq-connector_1  | 2021/04/12 09:10:37 Crawling for functions
rabbitmq-connector_1  | 2021/04/12 09:10:37 Successfully declared Queue OpenFaaS_my-delay-exchange_remind_me
rabbitmq-connector_1  | 2021/04/12 09:10:37 Successfully bound Queue OpenFaaS_my-delay-exchange_remind_me to exchange my-delay-exchange
rabbitmq-connector_1  | 2021/04/12 09:10:37 Crawling finished will now refresh the cache
rabbitmq-connector_1  | 2021/04/12 09:10:37 Update cache with 1 entries
rabbitmq-connector_1  | 2021/04/12 09:10:37  [*] Waiting for messages. To exit press CTRL+C
rabbitmq-connector_1  | 2021/04/12 09:10:42 Invocation for topic remind_me finished on 1 function(s)
rabbitmq-connector_1  | 2021/04/12 09:11:07 Crawling for functions
rabbitmq-connector_1  | 2021/04/12 09:11:07 Crawling finished will now refresh the cache
rabbitmq-connector_1  | 2021/04/12 09:11:07 Update cache with 1 entries
rabbitmq-connector_1  | 2021/04/12 09:11:36 Crawling for functions
rabbitmq-connector_1  | 2021/04/12 09:11:36 Crawling finished will now refresh the cache
rabbitmq-connector_1  | 2021/04/12 09:11:36 Update cache with 1 entries
rabbitmq-connector_1  | 2021/04/12 09:11:37 Invocation for topic remind_me finished on 1 function(s)
```

**Comment by oktapodia** [comment]
Same thing on the develop image

**Comment by oktapodia** [comment]
The http status code is always 200 as I don't know how to manage it (yet)

**Comment by Templum** [comment]
> The http status code is always 200 as I don't know how to manage it (yet)

Please be aware that OpenFaaS (Components) might actually alter the status code, could you check what you receive if you directly call the function via the OpenFaaS Gateway. 

Because from your logs  I can see the invocation going through and no warning is getting printed (about not being able to [ack delivery](https://github.com/Templum/rabbitmq-connector/blob/develop/pkg/rabbitmq/exchange.go#L111-L135)). 

Nevertheless, I will attempt to reproduce the issue later, from your screenshots it seems like you leverage the RabbitMQ UI to check the acknowledgment of the deliveries. Do you this on exchange level or queue level?

**Comment by oktapodia** [comment]
I've added some more information into the [client](https://github.com/Templum/rabbitmq-connector/blob/develop/pkg/openfaas/client.go#L167) to get `resp.StatusCode(), fasthttp.StatusOK` 

Here's the result
```
rabbitmq-connector_1  | 2021/04/12 10:17:06 Extra info: %!(EXTRA int=200, int=200)
```

**Comment by oktapodia** [comment]
> Do you this on exchange level or queue level?

At the queue level

I've double checked and https://github.com/Templum/rabbitmq-connector/blob/develop/pkg/rabbitmq/exchange.go#L113 is correctly returning `nil`, so the acknowledgment should be ok

Here's the options of my exchange:
```
{
      autoDelete: false,
      durable: true,
      arguments: { 'x-delayed-type': 'direct' },
    }
```

I am using the default option for the queue

**Comment by Templum** [comment]
@oktapodia Is the message raised as persistent?  Could you share your topology & options you use the message producer?

**Comment by Templum** [comment]
![Screenshot 2021-04-12 180640](https://user-images.githubusercontent.com/7703616/114425940-d7feff00-9bb9-11eb-8c67-b04fb6c753e7.png)

For me every message was acked, I could not reproduce your issue.

**Comment by oktapodia** [comment]
Ok I think we are not speaking about the same one.

I did declare the queue `remind_me` on the exchange `my-delay-exchange`.
The rabbitmq connector created the queue `OpenFaaS_my-delay-exchange_remind_me`.
I am sending the rabbitmq messages to the queue `remind_me`.
The rabbitmq connector is listening this message and processing it through the queue `OpenFaaS_my-delay-exchange_remind_me` and is correctly acknowledge

The issue is that, in the queue `remind_me`, the message is still there and is not processed

Does that makes sense?

**Comment by Templum** [comment]
@oktapodia thanks for the clarification, but that is something not related to this connector. Sadly I'm not that familiar with RabbitMQ, but I assume it stays in your queue as no consumer is lacking on the specific queue. 

The connector as you stated uses its own queue on which it sends out the ack. It does not interact with any other queue. Also don't think that this would be the correct behavior. That aside, you should be able to send deliveries straight to exchange along with a routing key.

**Comment by oktapodia** [comment]
I see, thank you very much for your feedbacks, there was a confusion between a queue and a routine key on our end
