### ISSUE TITLE
[FR]Enable use of RMQ virtual host for connection

### ISSUE THREAD

**Issue by AmarjeetRaj** [Templum/rabbitmq-connector#118]
**Is your feature request related to a problem? Please describe.**
I would like to use RabbitMQ virtual host for connection as I have restricted access to RabbitMQ.

**Describe the solution you'd like**

1. Add environment variable RMQ_VHOST, eg: RMQ_VHOST:openfaas
2. Same can be utilized in getRabbitMQConnectionURL() in config.go for enabling virtual host
`fmt.Sprintf("amqp://%s:%s@%s:%s/%s", user, pass, host, port, vhost)`

**Comment by Templum** [comment]
Hello,
Sounds like a reasonable and straight forward request. Will implement it, please feel free to track this Issue for the progress. Will link the PR once created.

Best regards

**Comment by Templum** [comment]
@AmarjeetRaj your FR was implemented and merged to `develop`. Please try out the latest develop image and let me know if it works for you. The documentation was already adjusted, once I get positive feedback from you I will merge it into v1 and prepare a new release.

**Comment by AmarjeetRaj** [comment]
@Templum Thank you very much. Tried and successfully connected to RMQ using virtual host. Working as expected.

**Comment by Templum** [comment]
Released it as part of [1.0.2](https://github.com/Templum/rabbitmq-connector/releases/tag/v1.0.2)
