### ISSUE TITLE
Support basic auth for accessing authenticated gateway

### ISSUE THREAD

**Issue by Templum** [Templum/rabbitmq-connector#2]
In the same way functions in OpenFaaS Cloud access a secret to access the API Gateway's function list, we should enable this for the connector.

**Comment by alexellis** [comment]
Hi Simon, I would consider this feature essential now.

I've put together a small SDK which may be useful for you - or if that's too much work to adopt, then there's also the Kafka connector to which I added auth recently.

SDK example: 
https://github.com/openfaas-incubator/connector-sdk/blob/master/cmd/tester/main.go

Alex

**Comment by Templum** [comment]
Hi @alexellis ,

Alright, I will use the SDK then. Based on what I saw in the code, there are some parts that need modification. For now, using the SDK I can only print the responses (Invoker), but I wanted to receive the answer. So I have the option to send it to an answering queue. 

Another thing is that I currently experience issues with importing `github.com/openfaas-incubator/connector-sdk/types`. It breaks the dep tool, as there is no main. I defined it in my toml with

```
[[constraint]]
  name = "github.com/openfaas-incubator/connector-sdk/types"
  version = "0.1.0"
```

**Comment by alexellis** [comment]
You should be able to vendor the types package directly without needing to access a main package. 👍 

I'd consider this work high priority.

**Comment by Templum** [comment]
Hi @alexellis ,

Thanks for your information, I still have a way to go in regards to Golang. So I was able to use the types directly as you mentioned, a local test was also successful. The only thing missing now is to update the documentation and the docker-compose & K8S files.

**Comment by alexellis** [comment]
Hi Simon,

Glad to hear about the progress. Once ready I'd suggest doing a "Release" through the GitHub Releases page on this repo.

Please feel free to reach out for help, advise or to ask questions on our Slack community any time you need.

Alex

**Comment by Templum** [comment]
Hello @alexellis ,

I performed the release it is now also available @ DockerHub with the tags `latest`, `stable` & `0.1.0`. 
It includes the necessary code for Basic Auth. Further, the documentation was updated to reflect this.
