### ISSUE TITLE
[BUG] OpenFaas functions are not getting invoked everytime there is a message for that topic

### ISSUE THREAD

**Issue by milly21** [Templum/rabbitmq-connector#26]
# General Information

**Environment**
OpenFaas is deployed locally on kubernetes(using Minikube)
Rabbitmq and rabbitmq connector is deployed on on kubernetes(using Minikube)

**Connector Version**
Latest version

# Bug Details

**Describe the bug**
When I send messages to different topics, the OpenFaas function is not getting invoked every time.  
**Expected behaviour**
I expect OpenFaas function to get invoked every time there is a message for that topic to which openfaas function is subscribed.

**Steps to Reproduce**
Set RMQ_TOPICS: "input,output"
Using faas-cli to deploy OpenFaas function 
faas-cli store deploy Colorization --annotation topic="output"
faas-cli store deploy fillet --annotation topic="input"

Checking whether function is invoked or not with faas-cli list

Sending messages to the OpenFaaSQueue and topics(input, output) with a python client.

Please let me know if you need any more information.

**Comment by milly21** [comment]
Looked at Rabbitmq connector logs and I am getting message"Should not happen" when the function is not getting invoked.

**Comment by Templum** [comment]
Alright, thanks for the input. I will try to reproduce it. 

I will get back to you in case I require further input.

**Comment by Templum** [comment]
@milly21 I was able to reproduce the issue. I'm currently working on a fix for this. I will ping you again, once it is finished. Further, I will also link the PR, so you should be able to see the progress.

**Comment by Templum** [comment]
@milly21 could you be so kind and retest if `templum/rabbitmq-connector:pr-27 ` resolves the issues you experience ?

**Comment by milly21** [comment]
Yes sure, I will test the changes.

**Comment by milly21** [comment]
Do I need to add OpenFaaS_Topic in the connector-cfg.yml file?

**Comment by Templum** [comment]
No it will now spawn an dedicated Queue per Topic. It basically Prefixes the topic with OpenFaaS.

**Comment by milly21** [comment]
Thank you. I just tested. It seems to be working well for me. I will do a load test as well.

**Comment by Templum** [comment]
Alright, I will later merge the PR. Thanks for the testing.
