### ISSUE TITLE
[Q]How to invoke async functions using rabbitmq-connector?

### ISSUE THREAD

**Issue by shivupoojar** [Templum/rabbitmq-connector#295]

**Comment by Templum** [comment]
This supporter currently only supports direct calls. So no async invocations are supported

**Comment by shivupoojar** [comment]
Thank you, but I could see tye methods for async invocation in openfaas pkg.

**Comment by Templum** [comment]
That's correct, but it's not actively used.

**Comment by shivupoojar** [comment]
I want to invoke long running functions via async which is best suitable.
Thinking of using it.

**Comment by Templum** [comment]
Feel free to create a PR implementing the usage. I will be happy to review it.
