### ISSUE TITLE
[FR] Support for ActiveMQ

### ISSUE THREAD

**Issue by lmorandini** [Templum/rabbitmq-connector#30]
Since both ActiveMQ and RabbitMQ support AMQP 1.0, is at all possible to use this connector with ActiveMQ? (I have to stick to ActiveMQ, due to legacy code.)

**Comment by Templum** [comment]
@lmorandini thanks for raising this. I will look into this, currently [this ](ithub.com/streadway/amqp) lib is used for performing the connection. If it does support it, I can see what else is left to do.

Did you already tried out if it is working?

**Comment by lmorandini** [comment]
Thanks for the prompt reply @Templum. No, I did not try it, as I am just evaluating the use of OpenFaasS to replace a piece of our architecture. (More specifically, the component that has to be replaced takes a job description from ActiveMQ, performs the job, and then send the results back to ActiveMQ.

**Comment by Templum** [comment]
@lmorandini I see. Then I suggest that you come back to this issue, once you decided if you want to try it out. Then we can start the implementation process / see if it is necessary.

Although based on what you shared here, it seems that OpenFaaS should be a good match for your requirements.

**Comment by lmorandini** [comment]
It seems using ActiveMQ is not an option: the library your connector uses (https://github.com/streadway/amqp) supports only the AMQP 0.9.1 protocol (supported by RabbitMQ but not by ActiveMQ), and not AMQP 1.0 (which is supported by RabbitMQ via a plugin, and natively by ActiveMQ).

Any idea?

**Comment by Templum** [comment]
@lmorandini thanks for sharing. So there are go implementations for AMQP, but it would require me more or less from the ground up.

I will check if there is an lib out there, which is interface wise close to the one I'm using.

**Comment by lmorandini** [comment]
I am working on a Node.js implementation of a trigger/event generator based on ActiveMQ/STOMP (as I do not do Go). However, I noticed Go is the programming language of choice for OpenFaaS: do you see having a non-Go based implementation as an issue?

**Comment by Templum** [comment]
@lmorandini in my regular job I'm also working with node mostly, but I wanted to learn go to keep my mind fresh and open. But as OpenFaaS offers an REST API, there is no restriction to golang. It just makes it easier as you can reuse the upstream definitions, nevertheless let me know if you need help. I surely can help out a bit :)
