### ISSUE TITLE
[BUG] Wrong image name (in templates or in registry)

### ISSUE THREAD

**Issue by AntoninCamus** [Templum/rabbitmq-connector#31]
# General Information

**Environment**

Docker: [X]
Kubernetes: [X]
Other: []

# Bug Details
**Describe the bug**
In the kubernetes template (as well as in the docker compose), you use the docker image `templum/rabbitmq-connector:dev`. But this one is nowhere to be found, in fact on your registry there is a develop tag but no dev tag.

**Expected behaviour**
The image should either be tagged dev instead of develop (I find that better) or at least, the correct tag should be used inside of the docker-compose and kubernetes templates.

**Steps to Reproduce**
```bash
docker pull templum/rabbitmq-connector:dev                                      
# > Error response from daemon: manifest for templum/rabbitmq-connector:dev not found
docker pull templum/rabbitmq-connector:develop
#develop: Pulling from templum/rabbitmq-connector
#169185f82c45: Downloading [=======>                                           ]  342.8kB/2.207MB
#27ccad71c6e2: Downloading [============================>                      ]  179.8kB/310.3kB
#616561da8f52: Downloading [>                                                  ]  20.98kB/2.028MB
#1b94b286c8b4: Waiting 
```

**Comment by Templum** [comment]
Good catch, the branches are now used for the tags. Will update it.

**Comment by AntoninCamus** [comment]
Couldn't you simply rename develop to dev ?
About that, I find the naming of the branches a bit unclear. What is the difference between develop & master ? When we arrive on the repo, the default branch seems to be develop... what branch should we use ?

**Comment by Templum** [comment]
Actually, the repo is following the [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) Branching Model, hence the default branch for people visiting is develop.

However, the master is only used for releases or pre-releases.
