### ISSUE TITLE
[BUG] Connector crashes without reason

### ISSUE THREAD

**Issue by AntoninCamus** [Templum/rabbitmq-connector#32]
# General Information

**Environment**

Docker: []
Kubernetes: [X]
Other: []

**Connector Version**
Tag:develop

# Bug Details
**Describe the bug**
When I try to run the connector, I get crashes just after the connector succeed to connect to the RabbitMQ. I'm not sure if I missconfigure something, but eitherway the error message is not meaningfull at all `invalid character 'i' looking for beginning of value`. On the web, there is several mentions of this kind of error, related with a bad parsing of json.

**Environment**
My RabbitMQ is in version `3.6.9 ` and seems to be functionnal as it is a preprod of another program, and as I saw the connector successfully pop elements of the `OpenFaas_MyTopic` queue, but the function annotated with `topic: MyTopic` is never called.

**Full stack**
```
2019/07/23 12:25:03 OpenFaaS RabbitMQ Connector [Version: dev Commit: a76329e]
2019/07/23 12:25:03 Connector is in local mode will use the debug credentials
2019/07/23 12:25:03 Started Map Building. Be Aware it will take 30s until the first map is avaliable.
2019/07/23 12:25:03 1 Topic(s) are registered. Will be spawning 8 Worker(s) per Topic. 
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Binding Queue OpenFaaS_MyTopic to Exchange OpenFaasEx for Topic: MyTopic
2019/07/23 12:25:03 Subscriber agitated_leakey4 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber adoring_euclid0 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber sharp_stonebraker0 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber dreamy_davinci6 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber vibrant_curie9 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber kind_haibt9 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber gracious_edison3 is now listening for messages on MyTopic
2019/07/23 12:25:03 Subscriber tender_mcclintock9 is now listening for messages on MyTopic
2019/07/23 12:25:03  [*] Waiting for messages. To exit press CTRL+C
2019/07/23 12:25:33 invalid character 'i' looking for beginning of value
```

**Expected behaviour**
Either the program should be working if this is a bug, or the error message should be more meaningfull to help user to troubleshoot.

**Comment by Templum** [comment]
Thanks for reaching out please have a look at my comment on #12. The log message you shared here is typically for Auth Issues between connector and OpenFaaS

**Comment by AntoninCamus** [comment]
Thank you very much for your help. 
Would be an nice enhancement to warn about that (catching the error ?), instead of printing a strange parsing message.

**Comment by Templum** [comment]
Hi @AntoninCamus,

Well, it is an issue with the official [connector sdk,](https://github.com/openfaas-incubator/connector-sdk) which is related to [this](https://github.com/openfaas-incubator/connector-sdk/blob/master/types/function_list_builder.go#L28-L59) code section. Most likely I will remove the library at some point and leverage something self-written, however, for now, it is a limitation of the sdk. 

In regards to what you shared, [those ](https://github.com/openfaas-incubator/connector-sdk/blob/master/types/credentials.go#L12-L28)lines are responsible for reading in the secret from env. Sadly I can't spot something wrong, also the secret should be correctly formed according to [this ](https://github.com/openfaas/faas-provider/blob/master/auth/credentials.go#L38-L43)code.

Any logs popping up in regards to secrets?

**Comment by AntoninCamus** [comment]
Except in the pod (and the replicaset), where I've got the logs `2019/08/05 08:03:57 invalid character 'i' looking for beginning of value` I don't have any other suspicious things... so I don't really know where could I search.

The thing is that the pod don't crash until I send the first message on the queue, and just after I send it, it start crashing.

**Comment by Templum** [comment]
Could you share the complete k8s deployment yaml for the connector? And also how exactly you setup OpenFaaS

**Comment by Templum** [comment]
Closed due to inactivity
