### ISSUE TITLE
[FR] Publish new release

### ISSUE THREAD

**Issue by NKnusperer** [Templum/rabbitmq-connector#36]
**Is your feature request related to a problem? Please describe.**
Version `0.1.0` is bugged because of #26 and the `develop` tag cannot be used productive because of #32 (credentials are hard-coded when build as `dev` version).

**Describe the solution you'd like**
Publish a new `0.1.1` release to Docker Hub build from the current `develop` branch.
I build a Docker image locally for testing and now everything works as expected.

**Comment by Templum** [comment]
@NKnusperer thanks for pointing that out. Will perform a new image, should be available later this day as version `0.1.1`

**Comment by Templum** [comment]
Done - @NKnusperer could you be so kind and see if Release Image `0.1.1` does work for you as expected?

**Comment by NKnusperer** [comment]
Works 👍
