### ISSUE TITLE
[BUG] Zero functions found when hasNamespaceSupport is true but namespaces is empty.

### ISSUE THREAD

**Issue by hutton-capital** [Templum/rabbitmq-connector#50]
# General Information

I found that hasNamespaceSupport is true but the namespaces array returned from getNamespaces can be empty, leading to zero functions being found and added to the cache (as crawlFunctions iterates over the namespaces array)

**Environment**

Docker: [x]
Kubernetes: []
Other: []

**Connector Version**
Tag:0.1.2
Sha:

# Bug Details

I found that hasNamespaceSupport is true but the namespaces array returned from getNamespaces can be empty, leading to zero functions being found and added tot he cache as crawlFunctions iterates over the namespaces array.

I fixed this locally by adding a length check and default value to the namespaces array if it is returned empty from client.GetNamespaces() in cacher.go;

`
func (c *Controller) refreshTick(ctx context.Context, hasNamespaceSupport bool) {
	builder := NewFunctionMapBuilder()
	var namespaces []string
	var err error

	if hasNamespaceSupport {
		log.Println("Crawling namespaces for functions")
		namespaces, err = c.client.GetNamespaces(ctx)
		if err != nil {
			log.Printf("Received the following error during fetching namespaces %s", err)
			namespaces = []string{}
		}

		if(len(namespaces) < 1) {
			namespaces = []string{""}
		}
	} else {
		namespaces = []string{""}
	}

	log.Println("Crawling for functions")
	c.crawlFunctions(ctx, namespaces, builder)

	log.Println("Crawling finished will now refresh the cache")
	c.cache.Refresh(builder.Build())
}
`

**Expected behaviour**

I would expect any functions that contain the annotation "topic" to be found and added to the cache.

**Steps to Reproduce**

Using the Docker compose file and Local instructions, the figlet function was not added to the cache.

**Comment by Templum** [comment]
Thanks for reporting this @hutton-capital. Just to summarize:

> Giving OF supports multiple Namespaces (`hasNamespaceSupport==true`) it occurs that `c.client.GetNamespaces(ctx)` can return an empty `[]`?

In regards to your testing, can you please also share the OpenFaaS Version that you are using (especially the one of the gateway). That would be appreciated 🙏 

I will make sure to look into this issue later today and see if I can push out a fix right away.

**Comment by hutton-capital** [comment]
Hi,

Faas versions as requested;

openfaas/gateway:0.18.13
openfaas/basic-auth-plugin:0.18.13
openfaas/faas-swarm:0.8.5
nats-streaming:0.11.2
prom/prometheus:v2.11.0
prom/alertmanager:v0.18.0

**Comment by Templum** [comment]
I was able to determine the root cause, it seems like the Swarm Provider does not support namespaces. Instead of returning status indicating this, they are returning [200 with an empty list](https://github.com/openfaas/faas-swarm/blob/c3059c87645208c36bf7b63cac67014c9fd9f200/handlers/namespace.go). I created the PR #51 that should fix it.

**Comment by Templum** [comment]
@hutton-capital could you please test if `docker pull templum/rabbitmq-connector:pr-51` does resolve your issue ?

**Comment by hutton-capital** [comment]
Hi @Templum I have tested templum/rabbitmq-connector:pr-51 and it works fine. Thanks for the quick turnaround.

**Comment by Templum** [comment]
Thanks for testing this, I will merge then and it will be available on the latest branch. I will prepare an release for the upcoming days.

**Comment by Templum** [comment]
This change is now available via `docker pull templum/rabbitmq-connector:develop`
