### ISSUE TITLE
[BUG] Can not get openFaasFunction to trigger

### ISSUE THREAD

**Issue by jebos** [Templum/rabbitmq-connector#56]
# General Information

**Environment**

Docker: []
Kubernetes: [x]
Other: []

**Connector Version**
Tag:
Sha:

# Bug Details

**Describe the bug**
I try to configure the following setup:

-> OpenFaas Function send a message to RabbitMQ
-> RabbitMQ shall trigger another OpenFaas Function

In my RabbitMQ I have configured this:
```
Exchange: OpenFaasEx
Type | direct
durable:true 
```

```
Queue OpenFaaS_default
durable:true
```

Looking in RabbitMQ I can see the RabbitMQ Connector Consumers on the OpenFaas_default Queue

----

In my function I use this to send the message:

```
var exchange = "OpenFaasEx";
var routingKey = "default";
channel.assertExchange(exchange, "direct", {
        durable: true,
      });

channel.publish(exchange, routingKey, Buffer.from(event.body));
```

I can see the messages appear on the exchange.

My "to be called" function is deployed like this:

`faas deploy --replace=true --update=false -f default-message-function.yml --annotation topic="default"`

However I don't get any traffic on the queue nor a function call. I feel like I'm missing one link/configuration here...

**Expected behaviour**
default-message-function should be called

**Comment by jebos** [comment]
the log says

```
2020/08/19 09:58:24 Crawling namespaces for functions
2020/08/19 09:58:24 Crawling for functions
2020/08/19 09:58:24 Crawling finished will now refresh the cache
2020/08/19 09:58:24 Update cache with 1 entries
```

**Comment by jebos** [comment]
never mind... restarting the pod solved the issue...

**Comment by Templum** [comment]
@jebos thanks for the update, so I assumed you restarted the connector pod ?

**Comment by jebos** [comment]
Yes.
