### ISSUE TITLE
[BUG] Missing content-type in http request to openfaas function

### ISSUE THREAD

**Issue by jebos** [Templum/rabbitmq-connector#57]
# General Information

**Environment**

Docker: []
Kubernetes: [x]
Other: []

**Connector Version**
Tag: master
Sha:

# Bug Details

**Describe the bug**
The http request to open-faas does not provide a content-type header. This causes the lose of the request body when calling a nodejs based open-faas function  (based on https://github.com/openfaas/templates/tree/master/template/node12). This default template uses express to interpret the call and renders any body that comes without a content-type as invalid.

**Expected behaviour**
the http request should come with a content-type header. Idealy one should be able to set the header through the message properties on the queue.

**Comment by jebos** [comment]
I did some short hack here, to make it "work for my test" https://github.com/jebos/rabbitmq-connector/commit/51d81338249b849d728982463eea6d890fe41eb5

**Comment by Templum** [comment]
@jebos could you be so kind and check out if `$ docker pull templum/rabbitmq-connector:pr-58` works for you. It will leverage the MIME-Type of the RabbitMQ Delivery. Allowing the message sender to specify it.

Please let me know if it works for you or if you observe any side affects.

**Comment by Templum** [comment]
@jebos any updates ?

**Comment by jebos** [comment]
Hi, I got a bit distracted by other things... I plan to take a look today afternoon - we are pulling in your branch docker / image, but did not got to test its function yet

**Comment by jebos** [comment]
The PR works for me as expected.
