### ISSUE TITLE
[FR] Helm chart

### ISSUE THREAD

**Issue by zadigus** [Templum/rabbitmq-connector#60]
**Is your feature request related to a problem? Please describe.**

When I want to deploy the connector on my kubernetes cluster, I would like to deploy it by means of a helm chart, as I do for all my other microservices. Such a helm chart would obviously make the setup of the connector a bit simpler than hacking into the `yaml` configurations stored in the `artifacts` folder.

**Describe the solution you'd like**

A helm chart.

**Describe alternatives you've considered**

If I based purely on the code published to this repo, then I'd need to modify the yaml configuration files located in the artifacts folder and use `kubectl` to install them.

**Additional context**

I have written a helm chart that I can use for my own purposes. If you want, I'm happy to give it to you.

**Comment by Templum** [comment]
Hello @zadigus , thanks for raising this. I'm myself did not do much with helm so far, therefore a PR with your solution would be amazing. 

Please feel free to create a PR.

**Comment by zadigus** [comment]
Usually, people serve their helm charts on a webserver (e.g. github pages). This is not something I will setup in a PR (or at least not now). What I can do for you is I can provide you with a helm chart that'd be sufficiently generic for most uses. Would that be already good enough for you in a first step? If so, where would like the helm chart to come in? in the artifacts? at the project root?

I'll gladly open a PR for that.

**Comment by Templum** [comment]
@zadigus thanks for the pointer, will check the option of hosting it via GitHub pages out. I believe a PR without the necessary serve setup is fine.

So I saw that some projects have it under the `charts`-folder (e.g. OpenFaaS), not so sure if that is like "best" practice. What would you suggest? Maybe it makes sense to have it in a dedicated directory over having it in the generic folder.

**Comment by zadigus** [comment]
In my projects, I do define helm charts for my own microservices. In those cases I usually make up a `chart` folder where I lay down the chart. 

Most of the 3rd-party software I rely on have their charts defined in a separate repository (e.g. [bitnami](https://github.com/bitnami/charts)). Such repositories group together 3rd-party software of all kinds. The authentication and permission management software I use has its own repository for its helm charts (cf. [fusionauth](https://github.com/FusionAuth/charts)). That one would be an example of how you could do it on github.

On github I believe you have two options: either you create a dedicated repository for it or you define the github pages branch on your repository. 

I would suggest we place the chart in the `chart` folder at your repository's root in a first step. Nothing prevents you from moving it away later on. What do you think?

**Comment by zadigus** [comment]
@Templum I have a little question. Please excuse my lack of experience with your connector and rabbitmq. I am currently implementing a message queue for my e-shop and came up to the idea to use rabbitmq with your connector on openfaas. I never used rabbitmq before, therefore I need to know the following in order to make my helm chart productive:

- does it make sense to have multiple replicas of the rabbitmq-connector?

**Comment by Templum** [comment]
@zadigus thanks for your input, I agree and think we should go forward with having the chart folder on the root. An own repo sounds a bit overkill, given the "reach" of this project.

In regards to your second question. It should be possible to have multiple replicas, but to be fair I never tested it. So can't guarantee that there won't be any competing queries. Therefore I would suggest setting the default to 1 replica but leaving the option open.
