### ISSUE TITLE
[BUG] Contrary to what is advertised in the documentation, it seems like RMQ_QUEUE is never used in the code

### ISSUE THREAD

**Issue by zadigus** [Templum/rabbitmq-connector#64]
# General Information

**Environment**

Irrelevant.

**Connector Version**
Tag: v0.4.1
Sha: 43976f802d876418170012a9ca597513a33a4edc

# Bug Details

**Describe the bug**

It is no big deal. It seems like the documentation is not in sync with the code. In the [configuration options section](https://github.com/Templum/rabbitmq-connector/blob/v0.1.4/README.md#configuration-options-via-environment-variables), there is the mention of the environment variable `RMQ_QUEUE`. I was curious to see why this variable would be used and how. I made a full search in the codebase and found a use in the `config_test.go` only. And there it is only set to some value, it is then never used anywhere in the code.

**Expected behaviour**
I would expect that the environment variable `RMQ_QUEUE` be not part of the list of environment variables that is provided in the documentation. Instead, I would expect that it is somewhere mentioned how the queue name is generated. It is defined in `queue_consumer_factory.go` like this:
```go
func generateQueueName(topic string) string {
	const PreFix = "OpenFaaS"
	return fmt.Sprintf("%s_%s", PreFix, topic)
}
```
I would therefore expect a comment of the kind "the queue name is generated automatically and reads OpenFaaS_<topic-name>".

**Steps to Reproduce**

Irrelevant.

**Comment by Templum** [comment]
Thanks for raising this, I will correct the readme
