### ISSUE TITLE
[FR] Multi-Namespace Support for Lambda Invocation

### ISSUE THREAD

**Issue by zadigus** [Templum/rabbitmq-connector#77]
**Is your feature request related to a problem? Please describe.**

I have multiple k8s namespaces holding openfaas functions. In my k8s cluster, I am deploying my software for three different environments: staging, pre-production, and production. Each of those environments is deployed in a different k8s namespace. In each of those namespaces, I have potentially the same openfaas function names, but with different routing keys (e.g. in the staging environment the routing keys all start with `staging.`). The functions' definition is the same up to the k8s namespace they should land into.

In that setup, I have deployed openfaas in its own namespace, as well as rabbitmq. Both of them are used by my three environments. In each environment, I have deployed a rabbitmq-connector. So if I have my three environments up and running, I have overall 1 openfaas, 1 rabbitmq, and 3 rabbitmq-connector deployments.

Now, when rabbitmq-connector consumes the messages from the rabbitmq queue, it seems like it looks for the corresponding functions in the `openfaas-fn` namespace, i.e. the default [function namespace](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/values.yaml#L1) I've defined in my openfaas setup. 

I would like that rabbitmq-connector routes the messages to the corresponding function in the right namespace. 

**Describe the solution you'd like**

Probably a new environment variable could do the trick. I do not know exactly how rabbitmq-connector fetches information about the function it should deliver the consumes messages to. I can imagine that rabbitmq-connector uses the openfaas api and could probably get the function's namespace based on the routing key, but I have too little knowledge of the go language or the openfaas api to be really able to evaluate what solution would be best.

**Describe alternatives you've considered**

I could install openfaas and rabbitmq in each namespace but it would cost me more resources.

**Comment by Templum** [comment]
Hey @zadigus,

Thanks for reaching out. Generally speaking, the coding actually crawls all the namespaces (if the OpenFaaS provider does support it). However, after checking the coding it seems like it does not use it for the Invocation, which results in the behavior you are observing. 

Could you do me a favor and verify using the cache update message. If all of the functions from the different namespaces are picked up correctly?

Further, it would be lovely if you could share your OpenFaaS setup/configuration. Including version etc. so I can leverage it to verify the implementation. Further, please also mention the version of the connector you are using, as I recently finished work on #33 and soon will release it in version 1.0.0. Based on your version I would need to backport the feature.

That aside I will consider this for implementation.

**Comment by zadigus** [comment]
Currently, my system looks like this:

- openfaas gateway: 0.18.7
- openfaas alertmanager: 0.18.0
- openfaas faas-idler: 0.3.0
- openfaas nats: 0.17.0
- openfaas prometheus: 2.11.0
- openfaas queue-worker: 0.11.0
- rabbitmq: 3.8.11
- rabbitmq-connector: Version: v0.1.4 / Commit: 43976f8

**Comment by zadigus** [comment]
Regarding the cache update message, what do you want exactly, the `rabbitmq-connector`'s log file?

**Comment by Templum** [comment]
@zadigus thanks for sharing the details. That would be enough to get me going.
In regards to the log, I'm referring to [that line](https://github.com/Templum/rabbitmq-connector/blob/0e8fefc9d3594837eeeb36d826353e6e35e17d10/pkg/openfaas/cache.go#L54). It should print out the total number.

I will probably start working on this issue today or tomorrow, based on available time.

**Comment by zadigus** [comment]
Ok. Thank very much for your help. Very appreciated. Please find the logs of both [openfaas-gateway](https://github.com/Templum/rabbitmq-connector/files/6002697/gateway.log) and [rabbitmq-connector](https://github.com/Templum/rabbitmq-connector/files/6002696/rabbitmq-connector.log). On line 37 of the openfaas-gateway log, you see my issue.

**Comment by Templum** [comment]
@zadigus I already verified the behavior locally, please feel free to verify it using `templum/rabbitmq-connector:v0`. If you confirm the functionality, I will release a new version.

**Comment by zadigus** [comment]
@Templum it looks good to me. In the [gateway.log](https://github.com/Templum/rabbitmq-connector/files/6007771/gateway.log), you can see that now the `authorized-payment` function gets actually called. For me it's fine like this.

**Comment by Templum** [comment]
@zadigus will release a new version then.

**Comment by Templum** [comment]
🚀  Landed in [0.1.6](https://github.com/Templum/rabbitmq-connector/releases/tag/v0.1.6)
