### ISSUE TITLE
[FR] Connector should push message back to rabbitmq if function call fails

### ISSUE THREAD

**Issue by jebos** [Templum/rabbitmq-connector#89]
**Is your feature request related to a problem? Please describe.**
In case openfaas is busy (timeout), or there is an error (response !=2xx), it seems required that the connector pushes the message back to the queue in order to avoid data to be lost. 

**Describe the solution you'd like**
As mentioned, I think it would be nice if the message is pushed back to the queue, it may seem also a good idea to throttle execution in general (or in this case) to avoid highload loops, in case openfaas is not available.

**Describe alternatives you've considered**

**Additional context**
100.000 messages in a queue that shall be pushed through one single, not scaleable function (due to system limits and cost contrains - but not time constrains)

**Comment by Templum** [comment]
As offered earlier, will implement this feature. Follow this issue for any progress.

**Comment by Templum** [comment]
Created Draft PR #91, this feature will be made available to V1

**Comment by Templum** [comment]
@jebos would you willing to try out the change? Implementation and local testing were concluded. 
And I plan to later merge the PR, which should make it available through the following tags `develop` & `v1`. 

Please also see the following [section](https://github.com/Templum/rabbitmq-connector#topology-configuration), as this is the major difference between v0 & v1
